[project]

name = "Flask-Roots"
version = "1.0.0"
description = "Mike's common Flask tools."

authors = [
    {name = "Mike Boers", email = "flask-roots@mikeboers.com"}
]

license = "BSD-3-Clause"

classifiers=[
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3"
]

dependencies = [
    "Flask",
]


[project.urls]

Repository = "http://github.com/mikeboers/Flask-Roots"


[project.optional-dependencies]

mako = [
    "Flask-Mako",
    "Markdown",
    "PyHAML"
]

sqlalchemy = ["Flask-SQLAlchemy"]

mail = ["Flask-Mail"]

auth = [
        "Flask-Login",
        "Flask-ACL"
]

serve = [
    "gunicorn",
    "gevent"
]

images = ["Flask-Images"]

build = [
    "jsmin",
    "lesscpy",
    "watchdog"
]


[project.entry-points."flask.commands"]

build   = "flask_roots.cli.build:main"
migrate = "flask_roots.cli.migrate:main"
roots   = "flask_roots.cli.roots:main"


[project.entry-points."flask_roots"]

instance_path = "flask_roots.app:init_instance_path"
secret_key = "flask_roots.app:init_secret_key"

environ_config = "flask_roots.config:init_environ_config"
etc_config = "flask_roots.config:init_etc_config"

proxy_fix = "flask_roots.proxy:init_proxy_fix"

static = "flask_roots.static:init_static"
blank_static = "flask_roots.static:init_blank_static"
multi_static = "flask_roots.static:init_multi_static"

log_http_access = "flask_roots.logs:init_http_access_log"
log_format = "flask_roots.logs:init_log_format"
log_request_counter = "flask_roots.logs:init_log_request_counter"
log_no_werkzeug = "flask_roots.logs:init_no_werkzeug"
uuid_pixel = "flask_roots.logs:init_uuid_pixel"
log_stderr = "flask_roots.logs:init_log_stderr"
log_files = "flask_roots.logs:init_log_files"
log_mail = "flask_roots.logs:init_log_mail"
log_slack = "flask_roots.logs:init_log_slack"

signed_session = "flask_roots.session:init_signed_session"

login = "flask_roots.vendor:init_flask_login"
acl = "flask_roots.vendor:init_flask_acl"
mako = "flask_roots.mako:init_mako"
images = "flask_roots.vendor:init_flask_images"
sqlalchemy = "flask_roots.vendor:init_flask_sqlalchemy"
mail = "flask_roots.vendor:init_flask_mail"

route_re = "flask_roots.routing:init_route_re"
route_name = "flask_roots.routing:init_route_name"

error_templates = "flask_roots.errors:init_error_templates"


